name: ui
description: clind ui package.
publish_to: none

environment:
  sdk: 3.2.6
  flutter: 3.16.9

dependencies:
  flutter:
    sdk: flutter

  data:
    path: ../data
  domain:
    path: ../domain
  presentation:
    path: ../presentation

  di:
    path: ../di

  core_flutter_bloc:
    path: ../../../core/flutter_bloc
  core_util:
    path: ../../../core/util

  tool_clind_component:
    path: ../../../tool/clind/component
  tool_clind_theme:
    path: ../../../tool/clind/theme